name: Build python:3.11-slim+bash and export tar

on:
  workflow_dispatch:          # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: |
          docker buildx build \
            --tag python:3.11-slim-bash \
            --load \
            .

      - name: Export tar
        run: |
          docker save python:3.11-slim-bash | gzip > python311-slim-bash.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python311-slim-bash-tar
          path: python311-slim-bash.tar.gz
          retention-days: 7
